### ISSUE TITLE
PLZ Support playlist

### ISSUE THREAD

**Issue by Coder-Iro** [Techassi/vue-youtube-iframe#2]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/youtube/index.d.ts#L455-L564

There is playlist property in @types/youtube. Can you add support of playlist iframe?

**Comment by Techassi** [comment]
Hey,

I did fix a huge bug which resulted in the player parameters not being passed correctly to the player. Now you can use any supported parameter listed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/youtube/index.d.ts#L455-L564) or on the official developer site [here](https://developers.google.com/youtube/player_parameters#Parameters). The fix is available under the new version `1.0.6`

Exmaple code:

```vue
<template>
    <youtube-iframe :video-id="dQw4w9WgXcQ" :player-parameters="{
        playlist: 'dQw4w9WgXcQ,fC7oUOUEEi4'
    }"></youtube-iframe>
</template>
```

Let me know if everything works as expected.

**Comment by Coder-Iro** [comment]
```vue
<youtube-iframe :player-parameters="{
  listType: 'playlist',list:'PL-kUY2NcroAxDrAnUyEaeog7BX8Qj52uh'
}" no-cookie video-id="PgIzZfS9RP0"/>
```

I used like this. Everything works as expected.

**Comment by Techassi** [comment]
Good to hear! Thanks for your feedback...
