### ISSUE TITLE
How to reference the player in Vue3 Composition API ?

### ISSUE THREAD

**Issue by Dylan190774** [Techassi/vue-youtube-iframe#6]
Hi I'm doing the following in Vue3, with the Composition API:

      <youtube-iframe
        ref="youtube"
        :no-cookie="true"
        :player-width="360"
    />

_setup() :_ 

    const youtube = ref(null);

Now in `onMounted()` I can access the player's methods with : 

   `youtube.value.setSize(300,200)`

But sometimes this doesn't seem to work and I'm getting: 

_vue-youtube-iframe.esm.js?b672:181 Uncaught (in promise) TypeError: this.playerInstance.setSize is not a function_

Any idea how to fix this or a better way to reference the player in Vue3 (Composition API) ?

**Comment by Techassi** [comment]
If you don't need the size to be dynamic (just a static size) you can provide both the height and width as props like:

```vue
<youtube-iframe
    :video-id="YOUR_VIDEO_ID"
    :player-width="300"
    :player-height="200"
    :no-cookie="true"
></youtube-iframe>
```

Otherwise I'm not quite sure why the function `setSize` is not callable. 

The only reason this may happen is that there can be a short time window in which the component gets mounted but the player itself is not loaded completely, as the YouTube Player takes a short time to be embedded into the page and then be able to manipulated by functions like `setSize`.

But you can listen for the `ready` event and then trigger the resize via the `setSize` function. This event will fire when the player is embedded and functions can be called.

```vue
<youtube-iframe
    :video-id="YOUR_VIDEO_ID"
    :player-width="300"
    :player-height="200"
    :no-cookie="true"
    @ready="onReadyCallbackFunction"
></youtube-iframe>
```

In the upcoming `1.0.7` release better support for composable functions is planned. See [here](https://github.com/Techassi/vue-youtube-iframe#-upcoming-version-107) for more details.

**Comment by Dylan190774** [comment]
Thank you for your effort.

It's a strange problem. Sometimes this error comes up, and other times not. 
I needed `setSize` to respond to orientation change of a mobile device.

I put the resize in an eventlistener `orientationchange `now, which seems to work, but somehow calling `setSize `directly in onMounted gives an error, as if the player is not yet ready somehow.

Looking forward to the composable functions!

**Comment by Techassi** [comment]
Okay great!

As I mentioned above: the player component can be mounted (triggering `onMounted`) but the player itself is not yet embedded meaning functions like `setSize` will not work yet.

That's why I recommended the use of the `@ready` event which ensures the player is embedded and functions can be called.
